---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin"
webhook_url: 
sections:
- type: directory
  path: posts
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Page Content
- type: document
  path: page_data/index.md
  label: Home Page
- type: document
  path: page_data/about.md
  label: About ISHRAI
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
