---
new_page_extension: md
auto_deploy: false
admin_path: "/public/admin/"
webhook_url: 
sections:
- type: directory
  path: posts
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - blog-post
- type: heading
  label: Page Content
- type: document
  path: page_data/index.md
  label: Home Page
- type: document
  path: page_data/about.md
  label: About ISHRAI
- type: document
  path: page_data/whatwedo.md
  label: What We Do Data
- type: document
  path: page_data/contact.md
  label: Contact Info
- type: document
  path: page_data/partners.md
  label: Partner Data
- type: document
  path: page_data/team.md
  label: Team Data
- type: document
  path: page_data/donations.md
  label: Donations
  match: "**/*"
- type: document
  path: page_data/safehouse.md
  label: Safehouse
  match: "**/*"
- type: document
  path: page_data/gallery.md
  label: Gallery
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
